/**
 * 컴포넌트 Props 설정 파일
 * 
 * 생성일: 2025. 8. 30. 오후 6:51:29
 * 컴포넌트 타입: MAIN_BANNER
 * 스킨 ID: 57
 * 스킨 이름: e-commerce-02-mobile-slider
 * 버전: 1.1.1
 * 
 * 이 파일은 WithCookie 에디터에서 설정한 컴포넌트 속성을 포함합니다.
 * 스킨 개발 시 이 props를 상속하여 사용하세요.
 */

// 에디터에서 설정한 Props
const editorProps = {
  "deviceProperty": {
    "pc": {
      "banners": [
        {
          "text": "1일 섭취량은 100% \\n ~캡슐은 초미니로 작게",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.2487528644535879.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "7",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "광고",
          "adLink": "https://naver.com",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#ffffff",
          "adBackgroundColor": "#808080",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "적립10%",
            "추가증정"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "#ffffff",
          "categoryBackgroundColor": "#737373",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "0"
        },
        {
          "text": "정수기는 역시 코웨이 \\n 최대 6개월 반값할인",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.47719450258319873.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#ffffff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "상품권",
            "제휴카드"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "네이버페이로 결제하면 \\n~3,000p 적립",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.03544405688775454.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": false,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#fff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "네이버포인트"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "식닥 위의 예술 \\n ~빌레로이앤보흐~44%",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.9721419270604568.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "9",
          "hasBackground": false,
          "textColor": "#ededed",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#ffffff",
          "adBackgroundColor": "#787878",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "백화점동일",
            "단독특가"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "#ffffff",
          "categoryBackgroundColor": "#969696",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "나에게 맞는 유산균 \\n 드시모네 브랜드위크",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.318582967044279.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#fff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "CJ특가",
            "5% 카드할인"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "1일 섭취량은 100% \\n ~캡슐은 초미니로 작게",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.2487528644535879.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#fff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "적립10%",
            "추가증정"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "다이슨 에어랩id \\n 완벽 썸머 스타일링",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.38948664659953836.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#fff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "5%쿠폰",
            "2종사은증정"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "식닥 위의 예술 \\n ~빌레로이앤보흐~44%",
          "description": "",
          "url": "#",
          "icon": "https://withcookie.b-cdn.net/c/default/0.9721419270604568.jpg",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true,
          "showAd": true,
          "adImageUrl": "",
          "adText": "",
          "adLink": "#",
          "adPosition": "3",
          "adPositionPc": "3",
          "adPositionMobile": "3",
          "adTextColor": "#fff",
          "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
          "adBorderColor": "",
          "adOpacity": 1,
          "showCategory": true,
          "categories": [
            "백화점동일",
            "단독특가"
          ],
          "categoryPosition": "1",
          "categoryPositionPc": "1",
          "categoryPositionMobile": "1",
          "categoryTextColor": "white",
          "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
          "categoryBorderColor": "",
          "categoryFontSize": "14px",
          "categoryBorderRadius": "20px"
        },
        {
          "text": "ㅁㄴㄹㄴㄹㅇ",
          "description": "",
          "url": "#",
          "icon": "",
          "mediaType": "image",
          "videoUrl": "",
          "autoplay": true,
          "muted": true,
          "loop": true,
          "position": "5",
          "hasBackground": false,
          "textColor": "white",
          "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
          "buttonBgColor": "#ff6b6b",
          "buttonTextColor": "white",
          "buttonHoverColor": "#ff5252",
          "buttonText": "자세히 보기",
          "transparentButton": false,
          "buttonWidth": "auto",
          "buttonHeight": "auto",
          "showTitle": true,
          "showButton": true
        }
      ],
      "skin": "57"
    },
    "mobile": {}
  },
  "banners": [
    {
      "text": "1일 섭취량은 100% \\n ~캡슐은 초미니로 작게",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.2487528644535879.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "7",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "광고",
      "adLink": "https://naver.com",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#ffffff",
      "adBackgroundColor": "#808080",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "적립10%",
        "추가증정"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "#ffffff",
      "categoryBackgroundColor": "#737373",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "0"
    },
    {
      "text": "정수기는 역시 코웨이 \\n 최대 6개월 반값할인",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.47719450258319873.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#ffffff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "상품권",
        "제휴카드"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "네이버페이로 결제하면 \\n~3,000p 적립",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.03544405688775454.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": false,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#fff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "네이버포인트"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "식닥 위의 예술 \\n ~빌레로이앤보흐~44%",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.9721419270604568.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "9",
      "hasBackground": false,
      "textColor": "#ededed",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#ffffff",
      "adBackgroundColor": "#787878",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "백화점동일",
        "단독특가"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "#ffffff",
      "categoryBackgroundColor": "#969696",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "나에게 맞는 유산균 \\n 드시모네 브랜드위크",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.318582967044279.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#fff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "CJ특가",
        "5% 카드할인"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "1일 섭취량은 100% \\n ~캡슐은 초미니로 작게",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.2487528644535879.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#fff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "적립10%",
        "추가증정"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "다이슨 에어랩id \\n 완벽 썸머 스타일링",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.38948664659953836.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#fff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "5%쿠폰",
        "2종사은증정"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "식닥 위의 예술 \\n ~빌레로이앤보흐~44%",
      "description": "",
      "url": "#",
      "icon": "https://withcookie.b-cdn.net/c/default/0.9721419270604568.jpg",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true,
      "showAd": true,
      "adImageUrl": "",
      "adText": "",
      "adLink": "#",
      "adPosition": "3",
      "adPositionPc": "3",
      "adPositionMobile": "3",
      "adTextColor": "#fff",
      "adBackgroundColor": "rgba(0, 0, 0, 0.8)",
      "adBorderColor": "",
      "adOpacity": 1,
      "showCategory": true,
      "categories": [
        "백화점동일",
        "단독특가"
      ],
      "categoryPosition": "1",
      "categoryPositionPc": "1",
      "categoryPositionMobile": "1",
      "categoryTextColor": "white",
      "categoryBackgroundColor": "rgba(0, 0, 0, 0.7)",
      "categoryBorderColor": "",
      "categoryFontSize": "14px",
      "categoryBorderRadius": "20px"
    },
    {
      "text": "ㅁㄴㄹㄴㄹㅇ",
      "description": "",
      "url": "#",
      "icon": "",
      "mediaType": "image",
      "videoUrl": "",
      "autoplay": true,
      "muted": true,
      "loop": true,
      "position": "5",
      "hasBackground": false,
      "textColor": "white",
      "textShadow": "0 1px 2px rgba(0, 0, 0, 0.6)",
      "buttonBgColor": "#ff6b6b",
      "buttonTextColor": "white",
      "buttonHoverColor": "#ff5252",
      "buttonText": "자세히 보기",
      "transparentButton": false,
      "buttonWidth": "auto",
      "buttonHeight": "auto",
      "showTitle": true,
      "showButton": true
    }
  ],
  "skin": "57"
};

// 컴포넌트 기본 정보
const componentInfo = {
  id: "82dc7acc-113a-4fc2-a13d-500a87c58a64",
  type: "MAIN_BANNER",
  skinId: "57",
  skinName: "e-commerce-02-mobile-slider",
  version: "1.1.1"
};

// Props 병합 헬퍼 함수
function mergeWithEditorProps(customProps = {}) {
  return {
    ...editorProps,
    ...customProps,
    // 에디터 props를 우선시하려면 아래 순서를 바꾸세요
    // ...customProps,
    // ...editorProps
  };
}

// CommonJS 및 ES6 모듈 모두 지원
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    editorProps,
    componentInfo,
    mergeWithEditorProps
  };
} else if (typeof exports !== 'undefined') {
  exports.editorProps = editorProps;
  exports.componentInfo = componentInfo;
  exports.mergeWithEditorProps = mergeWithEditorProps;
}

// ES6 export (번들러가 지원하는 경우)
export { editorProps, componentInfo, mergeWithEditorProps };
export default editorProps;
