import type { Product } from '@/components/ui/ProductCard';
import type { SpecialtyBrandData } from '@/components/ui/SpecialtyBrandCard';

export const SPECIAL_BRAND_DATA: SpecialtyBrandData[] = [
    {
        path: '/',
        thumbnail: '/images/brand/specialty-brand-1.jpg',
        name: '설화수',
        description: '에프터 바캉스',
    },
    {
        path: '/',
        thumbnail: '/images/brand/specialty-brand-2.jpg',
        name: '헤라',
        description: '쿠선&프라이머',
    },
    {
        path: '/',
        thumbnail: '/images/brand/specialty-brand-3.jpg',
        name: '나스',
        description: '더 멀티플',
    },
    {
        path: '/',
        thumbnail: '/images/brand/specialty-brand-4.jpg',
        name: '빌리프',
        description: '촉촉 에디션',
    },
    {
        path: '/',
        thumbnail: '/images/brand/specialty-brand-5.jpg',
        name: '시세이도',
        description: '얼티뮨 세럼',
    },
];

export const SPECIAL_PRODUCT_DATA: Product[] = [
    {
        id: 1,
        categoryPath: '/category/food/health',
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        tagImage: '/images/tag/living-fair.png',
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집건강용품 특집건강용품 특집',
        price: 109000,
        discount: 10,
        purchases: 33584,
        likes: 100,
        flags: ['broadcast', 'delivery'],
        benefits: [
            { type: 'coupon', value: '10%' },
            { type: 'card', value: '무이자3' },
        ],
    },
    {
        id: 2,
        categoryPath: '/category/food/health',
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        tagImage: '/images/tag/luxury.png',
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집',
        price: 109000,
        discount: 50,
        purchases: 33584,
        likes: 340,
        flags: ['broadcast', 'tomorrow', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '50%' }],
    },
    {
        id: 3,
        categoryPath: '/category/food/health',
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집',
        price: 109000,
        purchases: 33584,
        likes: 77,
        flags: ['broadcast', 'weekend', 'delivery', 'return'],
    },
];

export const PRODUCT_DATA: Product[] = [
    {
        id: 4,
        categoryPath: '/category/fashion/clothing/tops',
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        stars: 4.7,
        reviews: 118,
        flags: ['broadcast', 'weekend', 'delivery', 'return'],
        benefits: [{ type: 'card', value: '무이자3' }],
    },
    {
        id: 5,
        categoryPath: '/category/fashion/clothing/tops',
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 45,
        stars: 4.7,
        reviews: 550,
        flags: ['broadcast', 'tomorrow', 'delivery', 'return'],
        benefits: [
            { type: 'coupon', value: '45%' },
            { type: 'card', value: '무이자3' },
        ],
    },
    {
        id: 6,
        categoryPath: '/category/fashion/clothing/tops',
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg', '/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },
];

export const CONSULTATION_PRODUCT_DATA: Product[] = [
    {
        id: 7,
        categoryPath: '/category/life',
        status: 'selling',
        brand: '한샘',
        type: 'consultation',
        thumbnails: ['/images/product/product-3.jpg'],
        title: '이지홈 인테리어',
        flags: ['broadcast'],
    },
    {
        id: 8,
        categoryPath: '/category/life',
        status: 'selling',
        brand: '노랑풍선',
        type: 'consultation',
        thumbnails: ['/images/product/product-3.jpg'],
        title: '큐슈 3일 #온천여행 #가을단풍',
        flags: ['broadcast'],
    },
];
